# This is the configuration used to check the rubocop source code.

Rails:
  Enabled: true

AllCops:
  Exclude:
    - bin/*

Documentation:
  Enabled: false

LineLength:
  Max: 99

HasAndBelongsToMany:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false
